name: Code Quality
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
  